commit:
  changelogs:
    - label: "commit.changelog"
      destination: "./CHANGELOG.md"

  changetypes:
    - label: "commit.type.add"
      name: "add"
    - label: "commit.type.chg"
      name: "chg"
    - label: "commit.type.fix"
      name: "fix"
    - label: "commit.type.dep"
      name: "dep"

  includes:
    - ruby-gem
    - ruby-rspec
    - ruby-standard
    - oss
    - git

  externals:
    - repo: "metabahn/commit-templates"
      private: true

git:
  ignore:
    - "tmp"

license:
  slug: mit
  name: "MIT"

project:
  slug: "llhttp"
  description: "Ruby bindings for llhttp."

  author:
    name: "Bryan Powell"
    email: "bryan@metabahn.com"
    homepage: "https://github.com/metabahn/llhttp/"

  copyright:
    attribution: "Metabahn"
    year: 2020

ruby:
  gem:
    namespace: "LLHttp"
    extra: |-2
        spec.files = Dir["CHANGELOG.md", "README.md", "LICENSE", "lib/**/*"]
        spec.require_path = "lib"

        spec.extensions = %w[ext/llhttp/extconf.rb]
